spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

jwt:
  jwtCookieName: abc
  jwtSecret: ======================ABC=Spring===========================
  jwtExpirationMs: 30000 #30s

abc:
  countries: {
    Netherlands: "NL",
    Germany: "DE",
    Belgium: "BE"
  }

